[package]
name = "tauri-temp"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"
default-run = "tauri-temp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "tauri_temp_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = "0.31"
dirs = "5.0"
tauri-plugin-global-shortcut = "2.3.1"
log = "0.4"
env_logger = "0.11"
chrono = "0.4"
once_cell = "1.19"
rusqlite = { version = "0.31", features = ["bundled"] }
tokio = { version = "1", features = ["rt-multi-thread", "net", "sync", "io-util", "time", "macros"] }
notify = { version = "7", features = ["macos_fsevent"] }
tokio-tungstenite = "0.24"
prost = "0.13"
prost-types = "0.13"
futures-util = "0.3"
http = "1.0"
ratatui = { version = "0.30.0", features = ["unstable-rendered-line-info"] }
crossterm = "0.29.0"

[build-dependencies]
tauri-build = { version = "2", features = [] }
prost-build = "0.13"

[dev-dependencies]
tempfile = "3"
filetime = "0.2"
